### ISSUE TITLE
Some BUGS I have found so far + SUGGESTIONS & REQUESTS

### ISSUE THREAD

**Issue by VOLKOUL** [DynamicTreesTeam/DynamicTrees-Terralith#1]
**BUGZZZ** (I am using Terralith v2.2.1a 1.18.2)
• Some biomes don't have trees at all (e.g: skylands)
• Some biomes have a mix of default Terralith trees and Dynamic Trees (e.g: siberian taiga)
• The majority of Terralith's biomes now have Quark's dynamic blossom trees basically everywhere (with this addon and quark's dynamic trees installed). It seems that their spawn rate is now calculated per trees and not per chunks (I think)

**SUGGESTIONS & REQUESTS**
With this addon installed some of Terralith's biomes seem rather... small, less mighty. The _trees_ are small and vanilla-ish in some cases. It would be MUCH better if such trees were replaced with mega variants, or even **custom variants**. The haze mountains, moonlight valley, yellowstone, all look kinda off / appear somewhat strange, incorrect, inaccurate.
Also, pls don't replace the trees in alpha islands in the future, it is nice to have such biome untouched :)

**P.S:** YOU ARE A GODSEND. You have no idea for how long we've been waiting for this. When I saw this I was like
 WOOOO YEEAH BABY THAT'S WHAT I'VE BEEN WAITING FOR!
No, really, the world feels complete now (almost). Lot's of Terralith's biomes are perfect now (e.g: steppe). So yeah, THANK U

**Comment by catter1** [comment]
Yes, this addon has not been completed at all yet. Still in beta, and we have a while to go with the custom trees, especially getting them placed in the corresponding biomes. Essentially all biomes will have a custom species, as far as I am aware. And yes, Alpha Islands will stay as they are :)

Glad you like the progress so far!

**Comment by VOLKOUL** [comment]
**AWESOME**, thank u)
Btw, to also _maybe_ make things easier Biomes O' Plenty trees could be used? Though that would make it an additional dependency

**Comment by djsimmonds** [comment]
i just did a second (alpha) update to fix some bugs (the skylands and siberian taiga you mentioned, also fractured savanna). regarding dt quark, it does not just apply to this add-on, and it is unclear why this is occurring in modded biomes- i discussed with DT devs, and they may revert from tag to category selectors for dt-quark to fix for the time being, so you can keep an eye out for updates (i have had to turn it off for the time being).

**Comment by djsimmonds** [comment]
if testing the new alpha, make sure to move the datapack fixes from available to the active section at the top of the list at world creation.

**Comment by VOLKOUL** [comment]
Ok, thanks!

**Comment by DeshiDesu** [comment]
I share the same sentiment with the OP. I love you guys for making this a reality😊😊😊
