### ISSUE TITLE
Spruce Trees Not generating Correctly

### ISSUE THREAD

**Issue by LordAkder** [DynamicTreesTeam/DynamicTrees-Terralith#2]
Hi, i am currently working on a Modpack update/Overhaul and I wanted to use Dynamic Trees in it.
I am playing on 1.19.2 Forge 43.2.20 and I am Using Dynamic Trees, DT Biomes O Plenty and DT Terralith and as soon as is added DT Terralith, nearly all Spruce Trees do not get generated correctly, only a few leaves in the Air get generated. 
You can even see this in the minecraft:taiga biome.

**Comment by liyumiq** [comment]
I have the same issue

**Comment by catter1** [comment]
Going to copy/paste what @djsimmonds said in Discord:

> the version currently available on CF for 1.19.2 is alpha and barely functional. we could troubleshoot but it's not worth it, as the actual beta version is essentially ready and will drop any day now (last couple of changes, and DT+ needs to have a couple fixes ported forward from 1.18.2 to prevent crashes).

**Comment by supermassimo** [comment]
Fixed in [1.1.0](https://legacy.curseforge.com/minecraft/mc-mods/dynamic-trees-terralith/files/4709266)
