### ISSUE TITLE
1.19.2-1.1.0 : Spruces do not generate

### ISSUE THREAD

**Issue by rilemko** [DynamicTreesTeam/DynamicTrees-Terralith#3]
Spruces do not generate in any of the vanilla (or modded) biomes in the last two BETA6 and BETA7. There is instead floating blocks of spruce leaves (screen 1). In addition, spruces that grow from a sapling no longer have leaves (screen 2).

Everything works perfectly in 1.0.4.

![2023-08-14_21 43 54](https://github.com/DynamicTreesTeam/DynamicTrees/assets/123899973/2e989825-9c64-463a-a468-8df9b168aaef)
![2023-08-14_21 45 34](https://github.com/DynamicTreesTeam/DynamicTrees/assets/123899973/a9a1cda6-793b-414e-baaa-0518af0e87d3)

**Comment by Harleyoc1** [comment]
I can't reproduce this. It's possibly caused by another mod or tree pack (but I couldn't say which or why)?

**Comment by rilemko** [comment]
True, since DT was the only change and everything works perfectly in 1.0.4, I didn't really look any further.
So the problem is caused by/with DT-Terralith-1.19.2-Alpha1. All spruces in all biomes are broken, other DT-trees seem to have no issues, either in vanilla or Terralith biomes.

Reproducible with DT-BETA6 or 7, Terralith and DT-Terralith-1.19.2-Alpha1.

Sorry for the lost time, at least you have the info!

**Comment by djsimmonds** [comment]
there have been a number of changes in DT and DT plus since DT-Terralith alpha came out. Now that the full featured beta is out, there is no longer any reason to use the alpha.
