### ISSUE TITLE
Axe doesn't seems to work on trees when this addon is used forge 1.20.1

### ISSUE THREAD

**Issue by DaftHunk** [DynamicTreesTeam/DynamicTrees-Terralith#7]
Hello, I'm using the latest version of DT.

With this mod enabled, axe are behaving like hand on DT trees (all of them).
Removing this mod fix this problem. 

Here is my log in case something is relevant : 
[latest.log](https://github.com/user-attachments/files/15891513/latest.log)

**Comment by supermassimo** [comment]
This has been fixed in 1.2.1

**Comment by DaftHunk** [comment]
Perfect, I can confirm it is fixed, thank you :)
