### ISSUE TITLE
Vanilla tree in terralith:cave/underground_jungle

### ISSUE THREAD

**Issue by Elnhomantia** [DynamicTreesTeam/DynamicTrees-Terralith#8]
![image](https://github.com/DynamicTreesTeam/DynamicTrees-Terralith/assets/87205079/e4b74345-4e4f-4bb1-95bf-8f49fd520837)

These tree are mangrove with Azaela leaves, and i've seen vanilla cherry too. All non DT tree

**Comment by Elnhomantia** [comment]
![image](https://github.com/DynamicTreesTeam/DynamicTrees-Terralith/assets/87205079/21dcd580-41ed-472e-aa3d-a8f381849d86)
mushrooms too

**Comment by supermassimo** [comment]
Underground biomes are not yet supported, we are working on it :)

**Comment by Elnhomantia** [comment]
okay, sorry for this post. Thanks a lot for doing this mod !
